from datetime import timedelta

DOMAIN = "scrutiny"
SCAN_INTERVAL = timedelta(minutes=15)

API_SUMMARY_ENDPOINT = "/api/summary"
API_DETAILS_ENDPOINT_FORMAT = "/api/device/{wwn}/details"

EVENT_TYPE_SMART_ATTRIBUTE_DEGRADED = "smart_attribute_degraded"

ATTRIBUTE_STATUS_PASSED = 0
ATTRIBUTE_STATUS_FAILED_SMART = 1
ATTRIBUTE_STATUS_WARNING_SCRUTINY = 2
ATTRIBUTE_STATUS_FAILED_SCRUTINY = 4
ATTRIBUTE_STATUS_KNOWN_MASK = (
    ATTRIBUTE_STATUS_FAILED_SMART
    | ATTRIBUTE_STATUS_WARNING_SCRUTINY
    | ATTRIBUTE_STATUS_FAILED_SCRUTINY
)
